
name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Execute-Unit-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Run Unit tests
      run: npm run test:unit
    - name: Display my SoftUni username
      run: echo 'nikola_dachev'
  
  Execute-UI-tests:

    runs-on: ubuntu-latest
    needs: Execute-Unit-tests

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Install playwright
      run: npx playwright install
    - name: Start Application
      run: npm run start &
    - name: Exacute UI tests
      run: npm run test:ui

  Deploy:
    runs-on: ubuntu-latest
    needs: Execute-UI-tests
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
        